####################################
# YoloV5模型权重路径
weight:  "weights/last2.pt"
# 输入图像的尺寸
input_size: 640
# 类别个数
class_num:  1
# 标签名称
class_name: ['bearing']
# 阈值设置
threshold:
  iou: 0.5
  confidence: 0.2
# 计算设备
# - cpu
# - 0 <- 使用GPU
device: '0'