####################################
# YoloV5模型权重路径
weight:  "weights/last_num.pt"
# 输入图像的尺寸
input_size: 640
# 类别个数
class_num:  11
# 标签名称
class_name: ['1', '3', '4', '5', '6', '7', '8', '9', '10', 'bearing', '2']
# 阈值设置
threshold:
  iou: 0.45
  confidence: 0.6
# 计算设备
# - cpu
# - 0 <- 使用GPU
device: 'CPU'